### ISSUE TITLE
Can't perform any Action

### ISSUE THREAD

**Issue by msantosh-rails** [DigixGlobal/ethereum-ruby#5]
Hi,

```
 While I perform any action, getting below error. Please help me.
```

757: unexpected token at '{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}

Thanks,
Santosh

**Comment by alexhanh** [comment]
+1 Facing the same error when using the IPC client. Works with HTTP.

Here's what the value of `read` is `"{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0xe4a\"}\n{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32600,\"message\":\"EOF\"}}\n"`. So it seems to actually contain two JSON responses, and so `JSON.parse(read)` fails here https://github.com/DigixGlobal/ethereum-ruby/blob/master/lib/ethereum/ipc_client.rb#L32

**Comment by alexhanh** [comment]
I believe the problem stems from using the `close_write` here https://github.com/DigixGlobal/ethereum-ruby/blob/master/lib/ethereum/ipc_client.rb#L29. Geth says:

```
I0625 11:21:05.501126 rpc/server.go:186] EOF
I0625 11:21:05.501410 rpc/notification.go:282] codec closed, stop subscriptions
I0625 11:21:05.501308 rpc/server.go:349] write unix /Users/alexhanh/EtherDev/data/geth.ipc->: use of closed network connection
```

Seems like Geth doesn't like closing of the connection. I was able to get it working using the following code:

``` ruby
socket = UNIXSocket.new(@ipcpath)
socket.puts(payload.to_json)
read = socket.gets
socket.close
```

**Comment by msantosh-rails** [comment]
Thank You alexhanh, It's working

**Comment by alexhanh** [comment]
Here's a working fork https://github.com/alexhanh/ethereum-ruby
- Fixed the IPC
- Refactored the client code
- Removed batching as it was broken
- Added missing RPC methods (including the management API)

I'm on OS X and I wonder if the Unix sockets work differently in Linux. Would appreciate if someone tests the fork on Linux.

Would also appreciate your input @tymat

**Comment by tymat** [comment]
@alexhanh That looks good.  Batching needs to be refactored to work with Homestead.  

Can you submit a pull request?

**Comment by alexhanh** [comment]
https://github.com/DigixGlobal/ethereum-ruby/pull/6

**Comment by ericsaupe** [comment]
I'm still having this issue. Following the README for compiling contracts I get this error:

```
NoMethodError: undefined method `compile_solidity' for #<Ethereum::IpcClient:0x007fd1326271a8>
Did you mean?  eth_compile_solidity
	from /Users/ericsaupe/.rvm/gems/ruby-2.3.3@oasis/bundler/gems/ethereum-ruby-36c78cefda5f/lib/ethereum/initializer.rb:9:in `initialize'
	from (irb):2:in `new'
	from (irb):2
...
```

Running locally all specs are failing as well. Many due to the error listed above.
